version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - ruby/bundle-install
      - run:
          name: DB Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:seed
      - run:
          name: Testing
          command: bundle exec rspec
